import '@/initializations/update-js-assets-path';
import '@/initializations/browser-detect';
import '@/initializations/import-jquery-plugins';
import '@/initializations/improve-window-events';

// libs
import '@/_libs/jquery-ui.min';
import '@/_libs/jquery.ui.touch-punch.min';
import '@/_libs/slick';
// Plugins
import '@/plugins/menu';
import '@/plugins/header';
import '@/plugins/BackToTopButton';
import '@/plugins/Slide';
import '@/plugins/SlideSlick';
import '@/plugins/Popup';
import '@/plugins/SlideSwiper';
import '@/plugins/ChangingTab';
import '@/plugins/QuantityButton';
import '@/plugins/ShoppingCart';
import '@/plugins/AddProductToCart';
import '@/plugins/Cart&Bag/ProductCart';
import '@/plugins/ReactIcon';
import '@/plugins/RatingStar';
import '@/plugins/SelectProvince';
import '@/plugins/Checkout';
import '@/plugins/Order';
import '@/plugins/OrderView';
import '@/plugins/FormatPrice';
